### ISSUE TITLE
npm package is not found.

### ISSUE THREAD

**Issue by wjh000123** [SkyAPM/SkyAPM-nodejs#10]
Hi there,

have you published this package to npm? I can't install it by ```npm install skywalking-nodejs```.

**Comment by ascrutae** [comment]
The first version haven't publish yet. but it will publish in this week 🚀. and Thanks for your attention

**Comment by ascrutae** [comment]
@wjh000123 the The 0.1.0 version has published. Here is the npmjs address: https://www.npmjs.com/package/skywalking-nodejs
