### ISSUE TITLE
关于   Module._load

### ISSUE THREAD

**Issue by ckmilse** [SkyAPM/SkyAPM-nodejs#11]
您好，我看了一下代码，发现使用的是   Module._load ，本人基础不够，所以想请问一下 对于Node 9 上使用es6的 import 语法会不会有影响

**Comment by ascrutae** [comment]
ES的import语法已经从Node 9 开始原生支持了，不过还处于Experimental阶段。具体使用参考[官方文档](https://nodejs.org/api/esm.html)
