### ISSUE TITLE
Nodejs call java can not see the call relationship

### ISSUE THREAD

**Issue by liuzhongh** [SkyAPM/SkyAPM-nodejs#12]
The frontend uses koa2 to provide front-end services in the nodejs environment. It call the back-end java services. According to their respective configurations, can see the corresponding front-end and back-end apps, but cannot see the front-end call the back-end link relationships.

**Comment by wu-sheng** [comment]
@ascrutae 0.1.1 should be only hotfix version. This is a requirement for new framework. Please move this to 0.2.0

**Comment by wu-sheng** [comment]
@liuzhongh Issue should be in English.

**Comment by ascrutae** [comment]
@wu-sheng  I had changed . Thanks

**Comment by ascrutae** [comment]
@liuzhongh  I try to read the code about `request` module and found that the module use the `http` module to request some stuff.  The `http` module has supported by  version 0.1.0. and I wrote a demo to test the function but it works. so I doubt that some difference with your's about the request module usage about my demo or The java agent don't support the plugin that  java application used , Could you give me an demo to reproduce this issue?

Here is the [demo](https://gist.github.com/ascrutae/19285ddfa20a52a69612184de739d3ed) with `request` module and screen snapshot:
<img width="845" alt="wx20180524-183459 2x" src="https://user-images.githubusercontent.com/12436447/40480544-72e9b8c0-5f81-11e8-84d4-0a5319e96f35.png">

**Comment by wu-sheng** [comment]
@ascrutae Glad to share, this is a good example. @liuzhongh Please compare your codes with this, and help to find out what is going on in your side.
