### ISSUE TITLE
SIGTERM

### ISSUE THREAD

**Issue by wandersonwhcr** [SkyAPM/SkyAPM-nodejs#124]
Hello,

First, TY for your package. I am learning a lot of Node.js reading the source. It is very clean.

Currently, I have doubts about stopping the agent. If I create a simple source, like this one:

```js
const agent = require('skyapm-nodejs');

agent.start({
  serviceName: 'foobar',
});

process.on('SIGTERM', function () {
  process.exit(0);
});
```

I can stop the process. Without `SIGTERM` handling, it will never stop.

Is it right? Is there something to gracefully stop the agent?

**Comment by wandersonwhcr** [comment]
BTW, I am trying to develop a plugin for `mongodb` and `fastify`.

**Comment by kezhenxu94** [comment]
> Is it right? Is there something to gracefully stop the agent?

There may be some timer/`setTimeout` that are not `.unref`ed, you can find them out and `unref` them, but basically, in reality, we usually `kill` the process actually

> BTW, I am trying to develop a plugin for mongodb and fastify.

Welcome to contribute
