### ISSUE TITLE
 Whether skyWalking8.0 is supported on skyapm-nodejs

### ISSUE THREAD

**Issue by EvanLjp** [SkyAPM/SkyAPM-nodejs#125]
Whether skyWalking8.0 is supported on skyapm-nodejs

**Comment by kezhenxu94** [comment]
Yes, but it's not released yet, please build from source yourself

**Comment by EvanLjp** [comment]
i don't find code on master branch

**Comment by kezhenxu94** [comment]
> i don't find code on master branch

What do you mean, the codes are there

**Comment by EvanLjp** [comment]
sorry i am wrong

**Comment by TJ666** [comment]
How to build from source code?

**Comment by ascrutae** [comment]
@TJ666 I will push 2.0.0 to NPM repository this weekend

**Comment by TJ666** [comment]
thx!
