### ISSUE TITLE
How to customize traceid generation rules？

### ISSUE THREAD

**Issue by TJ666** [SkyAPM/SkyAPM-nodejs#126]
How to customize traceId generation rules？For example, from the request header（Nginx/access gateway will add uniq traceID），I want to get through traceId with the back end.

do me a favor,please.

**Comment by ascrutae** [comment]
I prefer to that thing which Nginx or access gateway added following SkyWalking's header protocol than changing the traceId generation rules

**Comment by EvanLjp** [comment]
support sw8 header is good way to pass traceId.
https://github.com/apache/skywalking/blob/master/docs/en/protocols/Skywalking-Cross-Process-Propagation-Headers-Protocol-v3.md
but in protocv3 ,there is not a useful way to only pass traceId rather than pass segment refenance.
in my mind.the protocol v3 only works when the  services are controled  by skywalking in downstream  or upstream .
![image](https://user-images.githubusercontent.com/31562192/88876757-8e9e9780-d256-11ea-98a3-60e5c07e8c57.png)

**Comment by ascrutae** [comment]
> the protocol v3 only works when the services are controled by skywalking in downstream or upstream .

Is that mean service register?  The sw8 had remove service register.

**Comment by EvanLjp** [comment]
no,in our case:

access gateway==> bff==> backend services

bff==> node services==> with skywalking node agent
backend services==>java services ==> with skywalking java agent
access gateway ==> no skywalking sdk

if  access gateway pass header with v3 protocol, but the access gatwway is not transform date to skywalking oap server?
the v3 header required parent segment information ,It's not meet

**Comment by wu-sheng** [comment]
We don't encourage people to use a trace id injection. You want to hijack the protocol, you could, but this is not our design goal.

**Comment by wu-sheng** [comment]
Please make the SkyWalking agent/SDK working with the downstream services, that would be better. Trace v3 protocol is not hard to implement and report.

**Comment by EvanLjp** [comment]
i know your mind,the case only in our company ,so we should to solve it by ourself @TJ666

**Comment by wu-sheng** [comment]
I have a feeling, you are not talking about trace id, you are talking about `Cross Process Correlation Headers Protocol`

https://github.com/apache/skywalking/blob/master/docs/en/protocols/Skywalking-Cross-Process-Correlation-Headers-Protocol-v1.md

This is fully customizable and implemented in the java agent already.
