### ISSUE TITLE
Node JS12 is supported by Skywalking 7.0.0

### ISSUE THREAD

**Issue by mailyathish** [SkyAPM/SkyAPM-nodejs#128]
We are planning to upgrade Node js version NodeJS08  from NodeJS12,  Currently we are running Skywalking 7.0.0 for backend.  Does this version supports on Node-Js12 or do we need to upgrade Skywalking to 8.0.0.

Could you please confirm.

**Comment by ascrutae** [comment]
Which version do you mean? The newest(2.0.0) one or 1.2.0?

**Comment by mailyathish** [comment]
We are looking to upgrade the Node-js version to  Node.js Node.js 12.18.3 from current Node.js 8.0.0.    Skywalk version support for Node.js 12.18.3.

**Comment by ascrutae** [comment]
I see, The support version of SkyWalking depends on the version of Node.js agent. The Node.js agent runs well in  12.18.3 version.

**Comment by mailyathish** [comment]
Thanks for confirming.
