### ISSUE TITLE
ContextCarrier.prototype.serialize should encode _parentService and _parentServiceInstance

### ISSUE THREAD

**Issue by TJ666** [SkyAPM/SkyAPM-nodejs#129]
ContextCarrier.prototype.serialize = function() {
    let traceContextArray = [];
    traceContextArray.push("1");
    traceContextArray.push(Base64.encode(this._traceId));
    traceContextArray.push(Base64.encode(this._traceSegmentId));
    traceContextArray.push(this._spanId);
    **_traceContextArray.push(Base64.encode(this._parentService));
    traceContextArray.push(Base64.encode(this._parentServiceInstance));_**
    traceContextArray.push(Base64.encode(this._parentEndpoint));
    traceContextArray.push(Base64.encode(this._addressUsedAtClient));
    return traceContextArray.join("-");
};

**Comment by ascrutae** [comment]
Ref: #130

**Comment by ascrutae** [comment]
Fixed
