### ISSUE TITLE
Nodejs agent segment not finish when high level QPS

### ISSUE THREAD

**Issue by TJ666** [SkyAPM/SkyAPM-nodejs#133]
Bug
Which version of SkyWalking, OS and JRE?
sw8 skyapm-nodejs 2.0.0
Which company or project?
baidu
What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.
When high level QPS, segment is not finish. New segment still has a parent trace context ,and share traceId.So in skywalking dashboard. a trace chain keeps grow, the number of span :10,100,1000 .....
node versionn v10.9.0
eggjs worker = 8

![image](https://user-images.githubusercontent.com/17919231/90152663-a4659e00-ddba-11ea-8a51-de49898219f5.png)
![image](https://user-images.githubusercontent.com/17919231/90152702-af203300-ddba-11ea-8e24-b0e5b7b6739c.png)
thx for help

**Comment by TJ666** [comment]
@ascrutae  thx for help

**Comment by ascrutae** [comment]
Got it , I will try to fix it.

**Comment by TJ666** [comment]
How's the progress？If there is any progress, please tell me~

**Comment by ascrutae** [comment]
I had reproduce this issue ,and I had fixed it. this issue will fixed in 2.0.1.
