### ISSUE TITLE
how to debug agent send data to server

### ISSUE THREAD

**Issue by sophister** [SkyAPM/SkyAPM-nodejs#42]
hi, I've setup my `nodejs` app according to [the doc](https://github.com/OpenSkywalking/skywalking-nodejs/blob/master/docs/install-agent.md), but I can't see any data on skywalking UI. How can I know node agent has send data to server or not?

**Comment by ascrutae** [comment]
Maybe you can find that data in Elasticsearch  of Collector. Next version I will try to add agent logger component  to print the agent log.

**Comment by ascrutae** [comment]
Current version doesn't print the agent log.

**Comment by ascrutae** [comment]
Ref: #43

**Comment by ascrutae** [comment]
@sophister  You can accord [the document](https://github.com/OpenSkywalking/skywalking-nodejs/blob/master/docs/how-to-active-agent-log.org) to output log. If you have any question, please open another issue.

**Comment by sophister** [comment]
@ascrutae thx 👍
