### ISSUE TITLE
nodejs监控数据在监控台上显示不稳定

### ISSUE THREAD

**Issue by djb19841006** [SkyAPM/SkyAPM-nodejs#44]
现象：
   1. nodejs服务器重启后 ，监控画面能看到nodejs访问数据。
   2. 过一段时间后，重新访问nodejs服务器，监控画面监控不到nodejs的访问数据。

**Comment by sophister** [comment]
嗯，我也遇到这个问题了，部署nodejs agent之后，一直在skywalking里看不到数据。不知道nodejs的agent，有在生产环境使用的案例么

**Comment by ascrutae** [comment]
Currently the Node.js agent doesn't support reconnect.  this bug will fix in next version

**Comment by ascrutae** [comment]
Ref: #49
