### ISSUE TITLE
Acquire the send data address from naming server

### ISSUE THREAD

**Issue by ascrutae** [SkyAPM/SkyAPM-nodejs#48]
Currently, Node.js agent only support redirect mode, and it cause that the agent cannot send data to collector when the redirect address is broke.

**Comment by wu-sheng** [comment]
SkyWalking wouldn't support naming in naming service either released v6 or further release. You can't find this service any more.

There are lots of ways to provide load balance and cluster mode. Widely used is putting a load balance service between agent and collector cluster.

I recommend you to close this issue, and focus on sw6 header and protocol, which are more important considering v6 GA is going to release soon.

**Comment by ascrutae** [comment]
just for 5.x. all 6.x feature will release in version 1.0.0

**Comment by wu-sheng** [comment]
Same reason, I mean it is not necessary to be done. In v5, still load balance is better choice in real environment.

**Comment by ascrutae** [comment]
Got it , close this issue.
