### ISSUE TITLE
Eggjs framework access APM, agent, master process has no data for Throughput, Response Time, SLA

### ISSUE THREAD

**Issue by a526672351** [SkyAPM/SkyAPM-nodejs#53]
![image](https://user-images.githubusercontent.com/5345266/52983256-34749280-3425-11e9-9605-5f6d191c67b0.png)

**Comment by ascrutae** [comment]
This issue is cause by the heart beat of instance data is incorrect,  this
issue will fix soon.

**Comment by ascrutae** [comment]
This issue fixed in 1.0.1
