### ISSUE TITLE
What is the difference between skyAPM-nodejs and elastic-apm-node?

### ISSUE THREAD

**Issue by yuxizhe** [SkyAPM/SkyAPM-nodejs#63]
What is the difference between skyAPM-nodejs and elastic-apm-node?

**Comment by wu-sheng** [comment]
I think we are not the right one to answer this question. SkyAPM-nodejs is an ecosystem project around Apache SkyWalking, and it follows skywalking's formats and protocols. The only right answer from us is `we have nothing same except we are in APM field`.

If you want to do competition or comparison,  then you should set the bars and rules, right?
