### ISSUE TITLE
No Service

### ISSUE THREAD

**Issue by ZhouBox** [SkyAPM/SkyAPM-nodejs#74]
1. I use 6.0.0-GA
2. use egg framework
![image](https://user-images.githubusercontent.com/10395321/54668742-96aadb00-4b2a-11e9-8ec7-ed9f532648be.png)
I log ,  The serivce register, but use web, is not, but Endpoint is OK!

![image](https://user-images.githubusercontent.com/10395321/54668793-b8a45d80-4b2a-11e9-9e86-3fd05e049e1f.png)

**Comment by ZhouBox** [comment]
?

**Comment by ascrutae** [comment]
Which version do you use, and could you post more detail about this issue?

**Comment by ZhouBox** [comment]
1.node 10.15.0
2.skywalking 6.0.0-GA
3.egg 2.20.1
4.skyapm-nodejs 1.1.0

**Comment by ZhouBox** [comment]
I found, timezone no same.
