### ISSUE TITLE
php start error

### ISSUE THREAD

**Issue by FlyLand** [SkyAPM/SkyAPM-nodejs#82]
Unable to load dynamic library '/usr/local/php/lib/php/extensions/no-debug-non-zts-20151012/skywalking.so' - /usr/local/php/lib/php/extensions/no-debug-non-zts-20151012/skywalking.so: undefined symbol: _ZN6google8protobuf8internal14AddDescriptorsEPKNS1_15DescriptorTableE in Unknown on line 0

extentions:
[root@localhost ~]# php -m | grep pro
protobuf
xhprof
[root@localhost ~]#

**Comment by wu-sheng** [comment]
This is nodejs agent project.
