### ISSUE TITLE
Unable to see any data on UI

### ISSUE THREAD

**Issue by ukrocks007** [SkyAPM/SkyAPM-nodejs#88]
### Question
- Skywalking UI is not showing any data with node js application.

___
### Bug
Build docker images with latest code and used docker for running on mac, OAP server starts and shows the UUID mentioned in the nodejs application, UI starts and gets connected with OAP Server but still no data on the UI.
___
### Requirement or improvement
- Please give a small demo of Skywalking UI with node application...

**Comment by wu-sheng** [comment]
Do you read the number of endpoint at UI?

**Comment by kakopappa** [comment]
Hi

I have the same issue. These are the steps 
1. Download 
https://www.apache.org/dyn/closer.cgi/skywalking/6.4.0/apache-skywalking-apm-6.4.0.zip

Unzip and run bin\startup.bat

2. Go to http://localhost:8080/ I can see a an blank dashboard

3. Run the nodejs example

`require('skyapm-nodejs').start({
    // Service name is showed in sky-walking-ui. Suggestion: set an unique name for each service, one
    // service's nodes share the same code.
    // this value cannot be empty.
    serviceName: 'test',
    // Collector agent_gRPC/grpc service addresses.
    // default value: localhost:11800
    directServers: 'localhost:11800'
});`

After refresh http://localhost:8080/  and still same.. 

Am i missing something ?

**Comment by ascrutae** [comment]
This issue haven't updated for a long time, Close this issue.
