### ISSUE TITLE
Need to republish to npm

### ISSUE THREAD

**Issue by Gorden-Wang** [SkyAPM/SkyAPM-nodejs#93]
Does this commit below was published to npm ? I download the last version 1.1.2， pls check it

https://github.com/SkyAPM/SkyAPM-nodejs/commit/c60395716783e3e5a51755ca60f4264c03f8e178

**Comment by kezhenxu94** [comment]
Try [1.2.0](https://www.npmjs.com/package/skyapm-nodejs)
